# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate negative log likelihood
#' 
#' @param x parameter vector
#' @param counts count vector
#' @param groups per-sample group label vector (0 or 1)
#' @param size_factors per-sample size factor
#' @param null_model boolean indicating whether or not to use a group coefficient
#' @name negativeLL_NBID
#' @export
negativeLL_NBID <- function(x, counts, groups, size_factors, null_model) {
    .Call(`_codaDE_negativeLL_NBID`, x, counts, groups, size_factors, null_model)
}

#' Calculate gradient
#' 
#' @param x parameter vector
#' @param counts count vector
#' @param groups per-sample group label vector (0 or 1)
#' @param size_factors per-sample size factor
#' @param null_model boolean indicating whether or not to use a group coefficient
#' @name gradient_NBID
#' @export
gradient_NBID <- function(x, counts, groups, size_factors, null_model) {
    .Call(`_codaDE_gradient_NBID`, x, counts, groups, size_factors, null_model)
}

#' Optimize the NBID model
#' 
#' @param theta_init initial parameter vector
#' @param counts count vector
#' @param groups per-sample group label vector (0 or 1)
#' @param size_factors per-sample size factor
#' @param null_model boolean indicating whether or not to use a group coefficient
#' @param maxit maximum optimization steps
#' @name optim_NBID
#' @export
optimize_NBID <- function(theta_init, counts, groups, size_factors, null_model, maxit) {
    .Call(`_codaDE_optimize_NBID`, theta_init, counts, groups, size_factors, null_model, maxit)
}

